name: whatisbert
channels:
  - default
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytorch
  - pandas
  - matplotlib
  - numpy
  - scikit-learn
  - tqdm
  - pip:
    - transformers
    - pytest