name: whatisbert
channels:
  - default
  - pytorch
dependencies:
  - python=3.7
  - pip
  - pytorch==1.4.0
  - pandas
  - jupyter
  - matplotlib
  - numpy
  - scikit-learn
  - tqdm
  - pip:
    - transformers==2.8.0
    - pytest